version: '3'

services:
  ubuntubase:
    build:
      context: ./ubuntubase
      dockerfile: Dockerfile
    image: ubuntubase:latest

  vscode:
    build:
      context: ./vscode
      dockerfile: Dockerfile
    image: vscode:latest
    depends_on:
      - ubuntubase

  flutter:
    build:
      context: ./flutter
      dockerfile: Dockerfile
    image: flutter:latest
    depends_on:
      - vscode

  command_runner:
    image: flutter:latest
    command: ["code", "--verbose", "--user-data-dir=/home/", "--no-sandbox"]
    network_mode: bridge
    shm_size: 4096m
    environment:
      - DISPLAY
      - PULSE_COOKIE=/tmp/pulse/cookie
      - PULSE_SERVER=unix:/tmp/pulse/native
      - XMODIFIERS
      - GTK_IM_MODULE
      - QT_IM_MODULE
      - DefaultIMModule=fcitx
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
    volumes:
      - /tmp/.X11-unix/X0:/tmp/.X11-unix/X0
      - /run/user/1000/pulse/native:/tmp/pulse/native
      - ~/.config/pulse/cookie:/tmp/pulse/cookie:ro
      - /run/user/1000/bus:/run/user/1000/bus
      - ~/flutter_container:/home/user
      - /dev/bus/usb:/dev/bus/usb
    privileged: true
    user: "${UID}"
